### ISSUE TITLE
Unable to find a specification for `MetalScope`

### ISSUE THREAD

**Issue by gautamsareriyamt** [ejeinc/MetalScope#2]
Unable to find a specification for `MetalScope`
PanoramaView  not implement in my project. plz help me

**Comment by junpluse** [comment]
Which method did you install MetalScope: CocoaPods / Carthage / manual?

If`import MetalScope` line in your code has no errors, please check whether the build target is iOS Simulator. Most APIs (including PanoramaView) in MetalScope does not support the iOS Simulator (as Metal is).
