### ISSUE TITLE
Google Cardboard optimizations?

### ISSUE THREAD

**Issue by stursby** [ejeinc/MetalScope#26]
First off, great lib here! 

So, I've got a stereo image demo running on an iPhone 7 with a Google Cardboard and it's looking pretty good, but a tad fuzzy/blurry. I was just curious if there were any settings or optimizations I could play with... Also, I tried loading my own equirectangular image in there, which didn't work so I stacked two of them on top of each other in Photoshop, but still not quite right. So I was wondering if you had any tips for creating assets for this lib.

Any thoughts would be much appreciated, thanks!

**Comment by junpluse** [comment]
Hi @stursby 

Thanks for your feedback, and sorry for the late reply 🙇 

For best quality:

- 4096×2048 for mono (2:1 aspect ratio) images
- 4096×4096 for stereo (1:1 aspect ratio) images

If your own image is mono, edit line 45 in `Examples/StereoImage/Sources/ViewController.swift`:

```swift
// from
panoramaView.load(#imageLiteral(resourceName: "Sample"), format: .stereoOverUnder)
// to 
panoramaView.load(#imageLiteral(resourceName: "YOUR_IMAGE_NAME"), format: .mono)
```

If 4096 pixels are still not enough for you, unfortunately we can not achieve further quality at this time.

**Comment by stursby** [comment]
@junpluse Ok, thanks!
